apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 80
    name: http
    targetPort: 9080
  selector:
    app: productpage
  type: LoadBalancer