apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: podinfo
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: podinfo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: podinfo
    spec:
      containers:
      - image: podinfo
        name: podinfo
        resources: {}
status: {}
